version: 2
updates:
  - package-ecosystem: nuget
    directory: /src/Snaply.App
    schedule:
      interval: weekly
      day: monday
    groups:
      app:
        patterns: ["*"]
    commit-message:
      prefix: build

  - package-ecosystem: nuget
    directory: /src/Snaply.Imaging
    schedule:
      interval: weekly
      day: monday
    groups:
      imaging:
        patterns: ["*"]
    commit-message:
      prefix: build

  - package-ecosystem: nuget
    directory: /tests/Snaply.Tests
    schedule:
      interval: weekly
      day: monday
    groups:
      tests:
        patterns: ["*"]
    commit-message:
      prefix: build

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: ci
